name: 将 Markdown 转换为 PDF

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码
      - name: 检出仓库
        uses: actions/checkout@v4

      # 步骤2：安装 Pandoc、LaTeX 和中文字体支持
      - name: 安装 Pandoc 和 LaTeX (含中文支持)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-chinese \
            fonts-noto-cjk

      # 步骤3：将 Markdown 转换为 PDF（支持中文）
      - name: 转换 Markdown 为 PDF
        run: |
          pandoc Menu.md \
            -o Menu.pdf \
            --pdf-engine=xelatex \
            -V mainfont="Noto Serif CJK SC" \
            -V geometry:margin=1in

      # 步骤4：上传生成的 PDF 作为构建产物
      - name: 上传 PDF 产物
        uses: actions/upload-artifact@v4
        with:
          name: Menu-PDF
          path: Menu.pdf

      # 【可选】步骤5：将 PDF 提交回仓库
      # - name: 提交并推送 PDF
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #     git add Menu.pdf
      #     git commit -m "CI: 自动生成 PDF" || echo "没有更改可提交"
      #     git push