name: 将 Markdown 转换为 PDF

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码
      - name: 检出仓库
        uses: actions/checkout@v4

      # 步骤2：安装完整的 TeX Live 发行版（包含 xelatex）
      - name: 安装完整的 TeX Live 和 Pandoc
        run: |
          sudo apt-get update
          # 安装完整的 texlive 发行版，确保包含 xelatex
          sudo apt-get install -y \
            pandoc \
            texlive-full \
            fonts-noto-cjk \
            fonts-noto

      # 步骤3：验证 xelatex 是否安装成功
      - name: 验证 xelatex 安装
        run: |
          which xelatex
          xelatex --version

      # 步骤4：将 Markdown 转换为 PDF（支持中文）
      - name: 转换 Markdown 为 PDF
        run: |
          # 创建一个临时的 LaTeX 头文件
          cat > chinese-header.tex << 'EOF'
          \usepackage{xeCJK}
          \setCJKmainfont{Noto Serif CJK SC}
          \XeTeXlinebreaklocale "zh"
          \XeTeXlinebreakskip = 0pt plus 1pt
          \setlength{\parindent}{2em} % 设置中文段落缩进
          EOF
      
          pandoc Menu.md \
            -o Menu.pdf \
            --pdf-engine=xelatex \
            -V mainfont="Noto Serif CJK SC" \
            -V geometry:margin=1in \
            -H chinese-header.tex

      # 步骤5：上传生成的 PDF 作为构建产物
      - name: 上传 PDF 产物
        uses: actions/upload-artifact@v4
        with:
          name: Menu-PDF
          path: Menu.pdf